version: '3'
services:
  mysql:
    container_name: docker_mysql
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_secret
      - MYSQL_ROOT_PASSWORD=secret_whale
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
    - ./data:/var/lib/mysql
  nginx:
    container_name: docker_nginx
    depends_on:
      - php-fpm
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    container_name: docker_php
    depends_on:
      - mysql
    build: ./images/php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
